package com.hdl.util;

public interface TimeConstant {
    int ONE_SECOND_MILLISECOND = 1000;
    int ONE_MINUTE_MILLISECOND = 60000;
    int ONE_HOUR_MILLISECOND = 3600000;
    int ONE_DAY_MILLISECOND = 86400000;
    int ONE_MINUTE_SECOND = 60;
    long ONE_HOUR_SECOND = 3600L;
    long ONE_DAY_SECOND = 86400L;
    int THREE_HOUR_MILLISECOND = 3 * ONE_HOUR_MILLISECOND;
    int FIVE_HOUR_MILLISECOND = 5 * ONE_HOUR_MILLISECOND;
}